# Generated by Django 5.1.6 on 2025-02-07 12:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("cast", models.JSONField(default=list)),
                ("genres", models.JSONField(default=list)),
                ("description", models.TextField()),
                ("poster", models.CharField(max_length=300)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
